### ISSUE TITLE
403 Forbidden? 

### ISSUE THREAD

**Issue by FelixRamirezJr** [tastycake/igdb_api#3]
Hello!

I am trying to use this gem for a Rails 5 application. In one of my controllers I am attempting to make a simple API call with the following code.

`def index`
    `    Igdb.connect('my_key_from_igdb')`
    `    @games = Igdb::Game.all`
`end`

Oddly, it is giving me a 403 forbidden error, like so:

`Igdb::Exception::Api (403 Forbidden):
  
app/controllers/games_controller.rb:5:in `index'
  Rendering /Users/mac/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
  Rendering /Users/mac/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
`
I have a feeling I am missing something simple... 
Anyways, I am looking forward to using this gem! So any help in pointing me in the right direction will be greatly appreciated!

**Comment by etorrey** [comment]
@FelixRamirezJr 

I had the same issue, here's how I got around it.

First you need to set your api url, which isn't really described in the README and should be updated:
`Igdb.set_api_url("https://api-whateveryournumberis.apicast.io")`

Then you need to monkey patch the headers to be correct:
`class Igdb::Requester`
`  class << self`
`    def request_headers`
`      Hash.new.tap do |headers|`
`        headers['Content-Type'] = 'text/json'`
`        headers['user-key'] = api.api_key`
`      end`
`    end`
`end`


You can save that in a file nearby and require it right after you require the gem. Ideally the gem is updated to send the right headers. Hope that helps.

**Comment by FelixRamirezJr** [comment]
@etorrey Thanks for the reply! I actually ended up forking the repository and just changed what I needed in the code. I also added a little to the API, because the name attribute for the games was missing. If anyone wants a working version of this API, feel free to use mine.

https://github.com/FelixRamirezJr/igdb_api

**Comment by fbermel** [comment]
Maybe make a PR out of your changes? This repo is referred to as the ruby wrapper to the igdb api in the igdb api documentation. Either the documentation needs to be changed or the wrapper has to be updated so it works again.
